<a href="https://colab.research.google.com/github/danbikiki/machine-learning/blob/master/20200820_%EA%B5%90%EC%B0%A8%EA%B2%80%EC%A6%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##교차검증
-교차검증의 의미

-실습

###방법 1. 홀드아웃
-데이터: 훈련데이터와 테스트데이터

     훈련데이터: 훈련데이터+검증데이터---> 테스트데이터

###방법 2. k폴드 교차검증
-데이터의 수가 적을 때 주로 사용

-Default 연산량 x k개만큼


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats
from sklearn.datasets import load_boston

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [15]:
%matplotlib inline
boston=load_boston()

print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [48]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [50]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [19]:
bostonDF=pd.DataFrame(boston.data,columns=boston.feature_names)
#feature_names는 각 열 이름 

bostonDF['PRICE']=boston.target
print(bostonDF.shape)

(506, 14)


In [47]:
bostonDF.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

###데이터 탐색
-시각화, 통계 검정

-변수 정의

CRIM per capita crime rate by town

ZN proportion of residential land zoned for lots over 25,000 sq.ft.

INDUS proportion of non-retail business acres per town

CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)

NOX nitric oxides concentration (parts per 10 million)

RM average number of rooms per dwelling

AGE proportion of owner-occupied units built prior to 1940

DIS weighted distances to five Boston employment centres

RAD index of accessibility to radial highways

TAX full-value property-tax rate per $10,000

PTRATIO pupil-teacher ratio by town

B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town

LSTAT % lower status of the population

MEDV Median value of owner-occupied homes in $1000’s

###머신러닝 모형 만들기

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

#x,y 분리
y_target=bostonDF["PRICE"]
x_data=bostonDF.drop(["PRICE"],axis=1,inplace=False)   #독립변수조정가능

#학습 데이터 만들기
x_train,x_test,y_train,y_test=train_test_split(x_data,y_target,test_size=0.2,random_state=1)

#모형 만들기-선형회귀
lr_model=LinearRegression()
lr_model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
#예측
y_preds=lr_model.predict(x_test)
y_preds

array([32.65503184, 28.0934953 , 18.02901829, 21.47671576, 18.8254387 ,
       19.87997758, 32.42014863, 18.06597765, 24.42277848, 27.00977832,
       27.04081017, 28.75196794, 21.15677699, 26.85200196, 23.38835945,
       20.66241266, 17.33082198, 38.24813601, 30.50550873,  8.74436733,
       20.80203902, 16.26328126, 25.21805656, 24.85175752, 31.384365  ,
       10.71311063, 13.80434635, 16.65930389, 36.52625779, 14.66750528,
       21.12114902, 13.95558618, 43.16210242, 17.97539649, 21.80116017,
       20.58294808, 17.59938821, 27.2212319 ,  9.46139365, 19.82963781,
       24.30751863, 21.18528812, 29.57235682, 16.3431752 , 19.31483171,
       14.56343172, 39.20885479, 18.10887551, 25.91223267, 20.33018802,
       25.16282007, 24.42921237, 25.07123258, 26.6603279 ,  4.56151258,
       24.0818735 , 10.88682673, 26.88926656, 16.85598381, 35.88704363,
       19.55733853, 27.51928921, 16.58436103, 18.77551029, 11.13872875,
       32.36392607, 36.72833773, 21.95924582, 24.57949647, 25.14

-mean_squared_error(mse):실제값과 예측값 차이 제곱 후 평균

-rmse: 실제 오류 평균보다 더 커지는 특성이 있어 루트를 씌움

In [38]:
mse= mean_squared_error(y_test,y_preds)
print(mse)

23.380836480270425


In [39]:
rmse=np.sqrt(mse)
print(rmse)

4.835373458200558


##k폴드 적용
-cross_val_score() 함수 활용 rmse구하기

-5 폴드값, 값이 

In [41]:
from sklearn.model_selection import cross_val_score
neg_mse_scores=cross_val_score(lr_model,x_data,y_target,scoring='neg_mean_squared_error',cv=5)
print(neg_mse_scores)

[-12.46030057 -26.04862111 -33.07413798 -80.76237112 -33.31360656]


In [43]:
#dnl neg_mse_scores이게 -로 나왔으니까 -1곱해줘야함
rmse_scores=np.sqrt(-1*neg_mse_scores)

print(rmse_scores)

[3.52991509 5.10378498 5.75101191 8.9867887  5.77179405]


In [45]:
avg_rmse=np.mean(rmse_scores)
avg_rmse

5.828658946215802

###추가실습

In [68]:
y1_target=bostonDF['PRICE']
x1_data=bostonDF[['LSTAT','CRIM']]
x1_train,x1_test,y1_train,y1_test=train_test_split(x1_data,y1_target,test_size=0.3,random_state=1)

lr_model=LinearRegression()
lr_model.fit(x1_train,y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [69]:
y1_preds=lr_model.predict(x1_test)
y1_preds

array([27.35484003, 27.66495603, 17.40495701, 26.85163958, 24.78823045,
       24.15594702, 29.85139874, 22.41619149, 18.18823707, 26.22616773,
       26.82537046, 29.93111346, 21.98712361, 24.96524615, 23.64678782,
       22.57405485, 12.57321315, 29.88327333, 27.44393399,  7.81209088,
       23.84129891, 19.18386716, 25.79206633, 28.58055869, 29.87787439,
       11.52421867, 15.96266963, 24.71026735, 27.56345705, 15.1150913 ,
       29.15206588, 17.70710884, 31.45742124, 18.89636796, 25.97932283,
       21.99655994, 17.92706559, 29.29380453, 12.15478465, 20.44146395,
       27.5213095 , 28.04344305, 27.25871109, 12.35592911, 17.47541079,
       13.22561329, 32.19369851, 18.76676389, 25.16923484, 24.61005469,
       23.43291593, 24.09739479, 29.40201654, 24.06953112,  7.81128691,
       28.05664645,  6.96485922, 28.67668813, 21.01341486, 30.49485198,
       20.0779293 , 28.2362446 , 15.96443695, 17.92525962,  7.92093885,
       29.55023795, 31.78522033, 26.36860054, 24.82181925, 23.59

In [70]:
mse1=mean_squared_error(y1_test,y1_preds)
print(mse1)

42.16174820063009


In [71]:
rmse=np.sqrt(mse1)
rmse

6.493207851334353

In [72]:
from sklearn.model_selection import cross_val_score
neg_mse_scores1=cross_val_score(lr_model,x1_data,y1_target,scoring='neg_mean_squared_error',cv=5)
print(neg_mse_scores1)


[-24.1255658  -41.4989152  -73.75755836 -51.38193113 -22.5313076 ]


In [73]:
rmse_scores1=np.sqrt(-1*neg_mse_scores1)
rmse_scores1

array([4.91177827, 6.44196517, 8.58822207, 7.16811908, 4.74671545])

In [74]:
rmse1=np.mean(rmse_scores1)
rmse1

6.37136000859139